Homework6
AlexanderBulychev/NoteApp pull request #8
Opened 2022-05-19 20:06 UTC by AlexanderBulychev

2022-05-22 09:29 UTC, bsciosedu requested changes

2022-05-23 06:08 UTC, AlexanderBulychev commented on NoteApp/Services/NetworkManager.swift
> +class Worker {
Done

2022-05-23 06:12 UTC, AlexanderBulychev commented on NoteApp/Services/NetworkManager.swift
> +                print(error?.localizedDescription ?? "No error description")
Удалил print

2022-05-23 06:22 UTC, AlexanderBulychev commented on NoteApp/ViewControllers/ListViewController.swift
> +                print(error)
Done

2022-05-24 07:51 UTC, AlexanderBulychev commented on NoteApp/Services/NetworkManager.swift
> +                print(error?.localizedDescription ?? "No error description")
Не совсем понял, что именно необходимо удалить:
Принт или вызов completion при неудаче.
Если удаляю принт свойство error остается необработанным.

2022-05-24 07:55 UTC, AlexanderBulychev commented on NoteApp/Services/NetworkManager.swift
> +    func fetchDataWithResult(with completion: @escaping(Result<[NetworkNote], NetworkError>) -> Void) {
Сделал 2 completion согласно рекомендации

2022-05-24 08:04 UTC, AlexanderBulychev commented on NoteApp/Models/Note.swift
> +        cellViewModels.append(contentsOf: newNotes.map { CellViewModel(note: $0) })
Есть затруднение с тем, как это лучше сделать.
Вызов данного метода связан с тем, что модель для Парсинга заметок из сети объявлена как структура,
а для ручного добавления и редактирования заметок я использую класс

2022-05-26 08:18 UTC, bsciosedu commented on NoteApp/Services/NetworkManager.swift
> +                print(error?.localizedDescription ?? "No error description")
Да нафиг вы вообще эти print'ы с ошибками ставите? Либо показывайте нормальную ошибку пользователю на экране, либо не обрабатывайте ошибку вообще. Поскольку в постановке задачи ничего не говорится об отображении ошибки, просто не обрабатывай ошибку.

2022-05-26 08:27 UTC, bsciosedu commented on NoteApp/Models/Note.swift
> +        cellViewModels.append(contentsOf: newNotes.map { CellViewModel(note: $0) })
Оставь как есть.

2022-06-22 08:15 UTC, merged